### ISSUE TITLE
Двойной слэш

### ISSUE THREAD

**Issue by mediafoks** [sergeytolkachyov/WT-Content-Image-Gallery#4]
Если путь к картинкам начать со слэша
``{gallery}/images/...{/gallery}``

то на выходе получаем двойной слэш
``<img src"//images/..." />``

Понятно, что в документации у вас указано, что нужно писать путь без начального слэша, но хотелось бы на всякий случай проверку на первый слэш. Люди по привычке пишут по-разному. Хотя и так работает, но всётаки.

**Comment by sergeytolkachyov** [comment]
Сделано в  v.1.2.2

**Comment by sergeytolkachyov** [comment]
@mediafoks есть личка? В телеге или где-нибудь?
